config/routes.rb
# frozen_string_literal: true

Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :roles
  end
end

app/models/spree/permission_set.rb
# frozen_string_literal: true

module Spree
  class PermissionSet < Spree::Base
    has_many :role_permissions # rubocop:disable Rails/HasManyOrHasOneDependent
    has_many :roles, through: :role_permissions
    validates :name, :set, presence: true
    scope :display_permissions, -> { where('name LIKE ?', '%Display') }
    scope :management_permissions, -> { where('name LIKE ?', '%Management') }
  end
end

app/models/spree/permission_sets/role_management.rb
# frozen_string_literal: true

# A Role Manager has all the access of a UserManager and the ability to manage Roles
module Spree
  module PermissionSets
    class RoleManagement < PermissionSets::Base
      def activate!
        can [
          :admin,
          :display,
          :create,
          :update,
          :save_in_address_book,
          :remove_from_address_book,
          :addresses,
          :orders,
          :items
        ],
          Spree.user_class

        # due to how cancancan filters by associations,
        # we have to define this twice, once for `accessible_by`
        can :update_email, Spree.user_class, spree_roles: { id: nil }
        # and once for `can?`
        can :update_email, Spree.user_class do |user|
          user.spree_roles.none?
        end

        cannot [:delete, :destroy], Spree.user_class
        can :manage, Spree::StoreCredit
        can :manage, Spree::Role
      end
    end
  end
end

app/models/spree/role_permission.rb
# frozen_string_literal: true

module Spree
  class RolePermission < Spree::Base
    belongs_to :role
    belongs_to :permission_set
  end
end

app/controllers/spree/admin/roles_controller.rb
# frozen_string_literal: true

module Spree
  module Admin
    class RolesController < ResourceController
    end
  end
end

app/views/spree/admin/roles/_form.html.erb
<div data-hook="admin_role_form_fields">
  <div class="row">
    <div class="col-4">
      <%= f.field_container :name do %>
        <%= f.label :name, class: 'required' %>
        <%= f.text_field :name, class: 'fullwidth title' %>
        <%= f.error_message_on :name %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="left col-6">
      <%= f.label nil, I18n.t("spree.display_permissions") %>
      <ul style="list-style-type: none; padding: 0; margin: 0;">
        <% Spree::PermissionSet.display_permissions.each do |permission| %>
          <li>  
            <%= f.check_box 'permission_set_ids', {checked: f.object.try(:permission_sets).include?(permission), multiple: true}, permission.id, nil %>
            <strong><%= permission.name %></strong>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="right col-6">
      <%= f.label nil, I18n.t("spree.display_permissions") %>
        <ul style="list-style-type: none; padding: 0; margin: 0;">
          <% Spree::PermissionSet.management_permissions.each do |permission| %>
            <li>
              <%= f.check_box 'permission_set_ids', {checked: f.object.try(:permission_sets).include?(permission), multiple: true}, permission.id, nil %>
              <strong><%= permission.name %></strong>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="clear"></div>
</div>

app/views/spree/admin/roles/edit.html.erb
<% content_for :page_title do %>
  <%= I18n.t("spree.editing_user_role") %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= link_to I18n.t("spree.back_to_roles_list"), spree.admin_roles_path, :icon => 'arrow-left', class: "btn btn-primary" %>
  </li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @role } %>

<%= form_for [:admin, @role] do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <div class="clear"></div>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/roles/index.html.erb
<% content_for :page_title do %>
  <%= I18n.t("spree.user_roles") %>
<% end %>

<% content_for :page_actions do %>
  <% if can?(:admin, Spree::Role) && can?(:create, Spree::Role) %>
    <li>
      <%= link_to I18n.t("spree.new_user_role"), new_admin_role_url, :icon => 'plus', :id => 'admin_new_role_link', class: "btn btn-primary" %>
    </li>
  <% end %>
<% end %>

<% if @roles.non_base_roles.any? %>
  <table class="index">
    <colgroup>
      <col style="width: 50%">
      <col style="width: 50%">
    </colgroup>
    <thead>
      <tr data-hook="role_header">
        <th><%= I18n.t("spree.name") %></th>
        <th><%= I18n.t("spree.permissions") %></th>
        <th class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @roles.non_base_roles.each do |role|%>
      <tr id="<%= spree_dom_id role %>" data-hook="rate_row" class="<%= cycle('odd', 'even')%>">
        <td class="align-center"><%=role.try(:name) || I18n.t("spree.not_available") %></td>
        <td class="align-center"><%= role.permission_sets.map(&:name).to_sentence %></td>
        <td class="actions">
          <% if can?(:update, role) %>
            <%= link_to_edit role, :no_text => true %>
          <% end %>
          <% if can?(:destroy, role) %>
            <%= link_to_delete role, :no_text => true %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="content row">
    <div class="content col-12">
      <div class= "no-objects-found">
        <%= I18n.t("spree.no_resource_found", resource: I18n.t(:other, scope: 'activerecord.models.spree/role')) %>
        <% if can?(:admin, Spree::Role) && can?(:create, Spree::Role) %>
          <%= link_to I18n.t("spree.add_one"), spree.new_admin_role_path %>!
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/spree/admin/roles/new.html.erb
<% content_for :page_title do %>
  <%= I18n.t("spree.new_user_role") %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= link_to I18n.t("spree.back_to_roles_list"), spree.admin_roles_path, :icon => 'arrow-left', class: 'btn btn-primary' %>
  </li>
<% end %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @role } %>

<%= form_for [:admin, @role] do |f| %>
  <fieldset class="no-border-top">

    <%= render :partial => 'form', :locals => { :f => f } %>

    <div class="clear"></div>

    <%= render :partial => 'spree/admin/shared/new_resource_links' %>

  </fieldset>
<% end %>